### PR TITLE
Various fixes

### LINKED ISSUE #23: Setting custom rows/columns number breaks grid selector
I've setup with success:
- medium-editor 5.14.2 
- medium-editor-tables 0.5.0.

It works good with MediumEditorTable default settings (rows: 10, columns: 10), but it breaks when I initialize MediumEditorTable with custom rows/column number.

Here an example with:
1. rows: 10, column: 2
2.  rows: 10, column: 4

issuetables

I also tried without success with medium-editor 5.5.1.

### LINKED ISSUE #25: Extension not working with latest Medium Editor version (5.15.0)
Hi, 
I think the table extension isn't working with the latest MediumEditor version (5.15.0)

This is what I did to test it out:
1 - Downloaded the latest version of ME and Table extension.
2 - On the ME folder opened the example custom-toolbar.html, added the toolbar extension, js and css, defined the toolbar and extension.
3 - Opened the html on the browser, the table button appears in the toolbar, when I click on it nothing happens.

I then tried the same html with the ME v5.6.2, that is being used on the demo (http://yabwe.github.io/medium-editor-tables/) and it works fine.

Just a small detail, there is a console.log on line 283, I think it was left by mistake. 

Thanks

### LINKED ISSUE #26: Remove unnecessary console.log
There is an uneeded console.log here: https://github.com/yabwe/medium-editor-tables/blob/master/dist/js/medium-editor-tables.js#L283.

### PR DESCRIPTION
**Pull request by linkesch**
fix #26 - remove console.log
fix #25 - grid not showing up
fix #23 - fix custom number of rows and columns

### CODE REVIEW

File: src/js/grid.js [hunk 1]
```diff
@@ -49,7 +54,9 @@ Grid.prototype = {
     },
 
     _html: function () {
-        var html = '<div class="medium-editor-table-builder-grid clearfix">';
+        var width = this.columns * 16 + 2,
```
Comment (nmielnik) [inline src/js/grid.js]: Where does the 16 come from?  If it doesn't make sense to call this out as a constant/option now, could you add a comment to explain where the number comes from and what its purpose is?

**Comment by nmielnik** [comment]
Thanks a ton for fixing this stuff up, I just had one comment and then you should merge this in!

File: src/js/grid.js (hunk 1 above)
Comment (linkesch) [inline src/js/grid.js]: You're right. I'll make it a constant. Width of the grid was previously hardcoded to 162px in css - 16px is width of one cell and 2px is width of border = 162px is width of the grid with 10 columns. Now the width is calculated dynamically depending on a number of columns.
